# 100 numpy exercises



#### 1. Import the numpy package under the name `np` (★☆☆)

In [37]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [38]:
print(np.__version__)
np.show_config()

1.26.1
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.3",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/opt/arm64-builds/include",
      "lib directory": "/opt/arm64-builds/lib",
      "openblas configuration": "USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC

/opt/homebrew/lib/python3.11/site-packages/numpy/__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [39]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [40]:
vector = np.zeros(10)
print("%d bytes" % (vector.size * vector.itemsize))

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [41]:
# python -c "import numpy; numpy.info(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [42]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [43]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [44]:
vector = np.arange(50)
vector = vector[::-1]
print(vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [45]:
vector = np.arange(9).reshape(3, 3)
print(vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [46]:
nonzero = np.nonzero([1,2,0,0,4,0])
print(nonzero)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [47]:
identMatrix = np.eye(3)
print(identMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [48]:
randMatrix = np.random.random((3,3,3))
print(randMatrix)

[[[0.17233283 0.92662531 0.20121622]
  [0.40904058 0.73049322 0.87571358]
  [0.54292955 0.6913646  0.00456921]]

 [[0.21036707 0.33566025 0.11811652]
  [0.56821257 0.23733073 0.73946733]
  [0.91869359 0.43618944 0.36471482]]

 [[0.71292574 0.87094036 0.29775015]
  [0.59102515 0.05138087 0.47592551]
  [0.46954549 0.19645415 0.72870534]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [49]:
array = np.random.random((10,10))
arrayMin, arrayMax = array.min(), array.max()
print(arrayMin, arrayMax)

0.0027377816229259277 0.9791294626814394


#### 14. Create a random vector of size 30 and find the mean(середнє) value (★☆☆)

In [50]:
vector = np.random.random(30)
m = vector.mean()
print(m)

0.5779818929003876


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [51]:
array = np.ones((10,10))
array[1:-1,1:-1] = 0    # зрізи 1:-1 з першого до передостаннього по х і далі по у
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [52]:
array = np.ones((5,5))
array = np.pad(array, pad_width=1, mode='constant', constant_values=0) #розширюємо масив навкруги pad_width=1 на 1 символ mode='constant константи constant_values=0 константи нулі
print(array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [53]:
print(0 * np.nan)
print(np.nan == np.nan)  #невизначене значення нічому не дорівнює 
print(np.inf > np.nan) #нескінченість більше за будьяке число
print(np.nan - np.nan) 
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1) # обмеження точності представлення дробових чисел тому можливо не рівні

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [54]:
matrix = np.diag(1+np.arange(4),k=-1)#діагональна матриця з масивом в діагонали але k=-1 нижче головної діагоналі
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard(шашки) pattern (★☆☆)

In [55]:
matrix = np.zeros((8,8),dtype=int)
matrix[1::2,::2] = 1 #заповнити 1 клітинки на непарних рядках і парних стовпчиках
matrix[::2,1::2] = 1 #заповнити 1 клітинки на парних рядках і непарних стовпчиках
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [56]:
print(np.unravel_index(99,(6,7,8)))#номер елементу по індексу

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [57]:
matrix = np.tile( np.array([[0,1],[1,0]]), (4,4)) #np.array([[0,1],[1,0]]) шаблон який ми повторюємо (4,4) скільки разів горизонталдьно та вертикально
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [58]:
matrix = np.random.random((5,5))
matrix = (matrix - np.mean (matrix)) / (np.std (matrix))# mean середнє значення елем матриці std стандартне відхилення елем матриці ну і нормалізация відніманням середнього від кожного елемента
print(matrix)

[[-1.82639055 -1.31572001 -0.1069419   0.64755623 -0.06002616]
 [ 1.13883642  1.29425758  1.12329396  0.25342306  0.02501168]
 [-1.91787207  1.36452703 -0.44534648 -0.38821401  0.98406395]
 [-0.03330082  0.90000562 -0.1382774  -0.22808639 -1.67942029]
 [ 1.08509623  0.66397442 -1.25482544  0.80667679 -0.89230144]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [59]:
rgba = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [60]:
matrix = np.dot(np.ones((5,3)), np.ones((3,2))) #скал.добуток
print(matrix)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate(*-1) all elements which are between 3 and 8, in place. (★☆☆)

In [61]:
array = np.arange(11)
array[(3 < array) & (array < 8)] *= -1 
print(array)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [62]:
print(sum(range(5),-1)) #складаємо всі значення в послідовності що починається з -1
from numpy import *
print(sum(range(5),-1))#-1 означає що сума буде проведена по останній осі

10
10


#### 27. Consider an integer vector Z, which of these expressions(вирази) are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [63]:
Z=np.array([1, 2, 3, 4, 5], dtype=int)
Z**Z #(возведення кожного елементу до такого ж степіня)legal
2 << Z >> 2 #(зсув бітів)legal
Z <- Z #(порівняння з від'ємним значенням)legal
1j*Z #(множення комплексного числ на вектор)legal
Z/1/1#(ділення на 1)legal
Z<Z>Z#(спроба порівняння вектору з самим собою, не має змісту)illegal

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0)) #0/0
print(np.array(0) // np.array(0)) #0 націло на 0 
print(np.array([np.nan]).astype(int).astype(float)) #масив з наном потім нан в інт понім в флоат 

nan
0
[-2.14748365e+09]


C:\Users\Админ\AppData\Local\Temp\ipykernel_13692\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Админ\AppData\Local\Temp\ipykernel_13692\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Админ\AppData\Local\Temp\ipykernel_13692\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
array = np.random.uniform(-10,+10,10) #масив з 10 ранд чисел в рівном діапазоні -10 10
print(np.copysign(np.ceil(np.abs(array)), array)) # абс -всі числа невід'ємні ceil округлення вгору copysign застосовує знак з array до значень з минулого кроку

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
array1 = np.random.randint(0,10,10)
array2 = np.random.randint(0,10,10)
print(np.intersect1d(array1,array2)) #повертає спільні елементи

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all="ignore") #всі помилки в ігнор
array = np.ones(1) / 0 #тест

_ = np.seterr(**defaults) #назад

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Админ\AppData\Local\Temp\ipykernel_13692\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding(відповідаючі) to the month of July 2016? (★★☆)

In [ ]:
array = np.arange('2016-07', '2016-08', dtype='datetime64[D]') #масив дат з 2016-07 по 2016-08
print(array)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B) #a+b результат в b
np.divide(A,2,out=A) 
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract(вилучити) the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
array = np.random.uniform(0,10,10) #масив додатніх чисел

print(array - array%1) #масив-дробна частина
print(array // 1)#цілочисельне ділення
print(np.floor(array))#округлення
print(array.astype(int))#парс інт
print(np.trunc(array))#відброс дробної частини

[7. 7. 2. 0. 6. 7. 3. 0. 0. 8.]
[7. 7. 2. 0. 6. 7. 3. 0. 0. 8.]
[7. 7. 2. 0. 6. 7. 3. 0. 0. 8.]
[7 7 2 0 6 7 3 0 0 8]
[7. 7. 2. 0. 6. 7. 3. 0. 0. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix = np.zeros((5,5))
matrix += np.arange(5) #до кожного рядка матриці + масив 0-4
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for x in range(10):
        yield x         #генератор повертає поточний стан х при кожній ітерації
array = np.fromiter(generate(),dtype=float,count=-1) #створення масиву зі значень повернених генератором(count=-1-юзати всі значення з генератора)
print(array)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
vector = np.linspace(0,1,11,endpoint=False)[1:] #створення рівномірно розподіленого масиву (endpoint=False остання точка невключна) [1:] - підмасив з індексу 1 і до кінця
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
vector = np.random.random(10)
vector.sort()
print(vector)

[0.08175358 0.20065119 0.32080753 0.54694975 0.55031503 0.63217422
 0.74492058 0.76691127 0.8051301  0.85736131]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
array = np.arange(10)
np.add.reduce(array) #reduce бере два елемента та приміняє до них операцію, в нашому випадку-суму

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
array1 = np.random.randint(0,2,5)
array2 = np.random.randint(0,2,5)

equal = np.array_equal(array1,array2) #поелементно рівність arr1 arr2
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
array = np.zeros(10)
array.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates(що представляють декартові кординати), convert them to polar coordinates (★★☆)

In [ ]:
matrix = np.random.random((10,2))
X,Y = matrix[:,0], matrix[:,1] #х-всі значення першого стовпця матриці у-другого
R = np.sqrt(X**2+Y**2) #відстань від початку корд.
T = np.arctan2(Y,X) #арктангенс
print(R)
print(T)

[0.84091513 0.30158261 0.58209178 1.30797524 1.00477644 0.42861709
 0.67802323 0.83843063 0.96468781 1.03394556]
[0.98486304 0.8954788  0.08423246 0.78206805 1.07489796 1.48206164
 1.04863894 0.4971746  1.21730145 0.50846974]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
vector = np.random.random(10)
vector[vector.argmax()] = 0
print(vector)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area(охоплюючими [0,1]x[0,1] область) (★★☆)

In [ ]:
array = np.zeros((5,5), [('x',float),('y',float)]) #2d масив з флоат полями х у 
array['x'], array['y'] = np.meshgrid(np.linspace(0,1,5), #meshgrid-створення сіток для значень х у linspace-5 рівномірних чисел від 0 до 1
                             np.linspace(0,1,5))
print(array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix(матриця Коші) C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y) #обчислює різницю між кожною парою елем з х у, створює двумірну матрицю різниць 1.0 /-піднести кожен елем матриці різниць до -1 степеня
print(np.linalg.det(C)) #визначник С 

3638.1636371179666


#### 48. Print the minimum and maximum representable(представиме) value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min) #int info
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min) #float info
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=float("inf")) #встановлення параметрів друку numpy щоб друкувались всі елементи масиву (параментр threshold = нескінченість)
array = np.zeros((40,40))
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
array = np.arange(100)
v = np.random.uniform(0,100) #рандомне число віл 0 до 100
index = (np.abs(array-v)).argmin()#абослютна різниця кожного елементу масиву та сгенерованого числа, потім індекс найменої обирається
print(array[index])

19


#### 51. Create a structured array representing(представляючий) a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
array = np.zeros(10, [ ('position', [ ('x', float, 1), #1-кть байт для зберігання значення
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(array)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/var/folders/l8/p6dnvr891g1_n7y5m003jg0h0000gn/T/ipykernel_18931/741156731.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  array = np.zeros(10, [ ('position', [ ('x', float, 1), #1-кть байт для зберігання значення


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
vector = np.random.random((100,2))
X,Y = np.atleast_2d(vector[:,0], vector[:,1]) #ділення вектору на масиви х та у(vector[:,0] всі рядки та 0 ставпчик-х vector[:,1] з у аналогічно)
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2) #матриця відстаней з матриць квадратів різниці координат 
print(D) # обрахунок відстані від кожної точки масиву до всіх інших

[[0.         0.21178004 0.78236829 0.55973988 0.61573842 0.461037
  1.00941551 0.77786263 0.16270145 0.20636069 0.24148014 0.43526726
  0.10010055 0.22811001 0.56469859 0.72545422 0.2525468  0.35220506
  0.56072678 0.34975736 0.29045543 0.96993802 0.35035574 0.94279005
  0.50645629 0.74773551 0.5463293  0.09502061 0.67367148 0.1475208
  0.09458896 0.32501091 0.72274956 0.86841027 0.82459094 0.11485061
  0.5160966  0.42363805 0.73969615 0.88451456 0.34960833 0.74991317
  0.41928078 0.42670634 0.66432425 0.51523924 0.37909127 0.43096925
  0.29197995 0.48632265 0.46856537 0.48913212 0.91484983 0.45055053
  0.63735145 0.29780735 0.65970225 0.80733891 0.32922941 0.23241386
  0.2768011  0.51069908 0.624635   0.28795307 0.42367912 0.24078278
  0.21058329 0.16743237 0.26965425 0.21702113 0.59656024 0.52185762
  0.23722306 0.85409388 0.20060916 0.08639836 0.4829583  0.35574581
  0.43400807 0.61527803 0.27262956 0.74767771 0.0579473  0.21470961
  0.2366813  0.48759117 0.25622458 0.1330556  0.461

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
array = (np.random.rand(10)*100).astype(np.float32)
Y = array.view(np.int32) #інтерпритує представлення array як цілі числа
Y[:] = array
print(Y)

[62  1 40 11  3 25 65 41 81 57]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
answ = np.genfromtxt(s, delimiter=",", dtype=np.int32) 
print(answ)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate(перерахування) for numpy arrays? (★★☆)

In [ ]:
array = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(array): #перебір індексів та значень в array
    print(index, value)
for index in np.ndindex(array.shape): #генерація індексів та їх використання для отримання значень по ним
    print(index, array[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10)) #створення двух сіток х у розмірами 10х10 
D = np.sqrt(X*X+Y*Y) #матриця з відстанями точок до початку кординат 
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) ) #розрахунок G по Гаусовському розподіленю(mu сер значення sigma стандартне відхилення)
print(G)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
array = np.zeros((n,n))
np.put(array, np.random.choice(range(n*n), p, replace=False),1) #заміна р рандомних елементів в області nxn на 1 replace=False-обрані р елементів не повторюються
print(array)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True) #обрахунок середнього значення з кожної строки х(axis=1) і повернення результату зі збереженням розмірності (keepdims=True)

print(Y)

[[-0.54584152 -0.18895417 -0.4852986   0.1253865   0.02684834  0.26165626
   0.30875271  0.29564729  0.32914907 -0.12734586]
 [ 0.38408564  0.39751296  0.07298757 -0.37304381 -0.18393311 -0.3488505
  -0.16975899  0.05751349 -0.22291161  0.38639836]
 [-0.00368652 -0.02692682 -0.49428225  0.32411476 -0.0827607  -0.13342627
  -0.06574915  0.38577294  0.08043616  0.01650786]
 [-0.03082327  0.08992154  0.30187826 -0.39037141 -0.30652111  0.18058704
   0.48838987 -0.41727748  0.31040705 -0.2261905 ]
 [-0.44666867  0.23360667  0.25318551 -0.45664186 -0.16051013  0.2011973
   0.37908706  0.13671574 -0.073154   -0.06681763]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
array = np.random.randint(0,10,(3,3))
print(array)
print(array[array[:,1].argsort()]) #повертає індекси відсортованих по другому стовпцю елементів і по індексах пересортовує строки в матриці

[[1 8 5]
 [6 2 3]
 [3 1 8]]
[[3 1 8]
 [6 2 3]
 [1 8 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
array = np.random.randint(0,3,(3,10))
print((~array.any(axis=0)).any()) #повертає булевий масив де елементи вказують чи є в стовпці хочаб одне ненульове значення ~ інвертує false на true, any повертає true якщо хоч в одному стовпці нема нема жодного не нал значення

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
array = np.random.uniform(0,1,10)
z = 0.5
m = array[np.abs(array - z).argmin()] #обрахунок абсолютних різниць між елементами масиву та z, argmin повертає індекс елем з найменшою абс різницею 
print(m)

0.48531687162693893


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None]) #створюється ітератор по А Б та пустому масиву щоб обробляти а і б одночасно 
for x,y,z in it: z[...] = x + y #x береться з А у з Б а z з пустого масиву і в z сума х та у (... копіювання даних)
print(it.operands[2]) #вивід пустого масиву заповненого z

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray): #нащадок np.ndarray(дефолт нампай масив)
    def __new__(cls, array, name):#викликається при створенні екземпляру класа
        obj = np.asarray(array).view(cls)#view повертає ndarray типу NamedArray
        obj.name = name
        return obj

arr = NamedArray(name="some name", array = np.zeros((5,5))) 
print (arr.name)

some name


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
vector = np.ones(10)
indices = np.random.randint(0,len(arr),20) #масив довжиною вектора

np.add.at(vector,indices,1) #до кожного елементу вектора додаємо 1 стільки раз скільки його індекс є в масиві індексів
print(vector)

[2. 1. 3. 4. 3. 1. 6. 3. 1. 6.]


#### 65. How to accumulate(накопичувати) elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1] #масив індексів
F = np.bincount(I,X) #якщо індекс з І зустрічається в Х то не 0 в F , а число або сума чисел які стоять в Х над відповідними числами (1=1+6=7)
print(F)
#Функція np.bincount підраховує кількість входжень кожного індексу в масиві та сумує відповідні значення з масиву X.

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte) #тривимірний масив розміром (256, 256, 3) елементи від 0 до 3-індекси кольорів (RGBA)

colors = np.unique(I.reshape(-1, 3), axis=0)  #I преобразується в масив (65536, 3) потім unique шукає унікальні рядки в масиві, унікальний рядок-унікальний колір (-1 рахує к-ть елем в мас для перетворення 3д масиву в 2д, 3-розмір строки матриці)
 
n = len(colors) #колво унікальних кольорів #colors-RGB
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1)) #сумування елементів A по двом останнім осям , результат масив  (3, 4) де кожен елемент=сума елементів A по двом останнім осям
print(sum)

[[61 56 47 55]
 [49 49 58 53]
 [79 37 46 32]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets(підмножини) of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,10) #вектор
print(D)
S = np.random.randint(0,10,10) #індекси
print(S)
D_sums = np.bincount(S, weights=D) #робим бінкаунт для вектору але індекси не по порядку а так як вони в S проставлені(якщо в S на нульовому індексі 6 то ми в бінкаунт пишемо на індекс 6 додаєм число 0ового індексу з D)
print(D_sums)
D_counts = np.bincount(S) #звичайний бінкаунт S
print(D_counts)
D_means = D_sums / D_counts 
print(D_means)

[0.55043682 0.78119739 0.22195139 0.65982506 0.03996857 0.18185778
 0.66940382 0.76924288 0.81694781 0.24471337]
[7 0 1 1 2 4 5 9 0 1]
[1.59814519 1.12648982 0.03996857 0.         0.18185778 0.66940382
 0.         0.55043682 0.         0.76924288]
[2 3 1 0 1 1 0 1 0 1]
[0.7990726  0.37549661 0.03996857        nan 0.18185778 0.66940382
        nan 0.55043682        nan 0.76924288]


C:\Users\Админ\AppData\Local\Temp\ipykernel_19564\2520671469.py:9: RuntimeWarning: invalid value encountered in divide
  D_means = D_sums / D_counts


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
#генерує масив розміром (5, 5), де кожен елемент масиву є випадковим дійсним числом з рівномірного розподілу на інтервалі [0, 1].
np.diag(np.dot(A, B)) #вилучає діагональні значення з результату скалярного добутку матриць


array([0.61858527, 1.8140513 , 2.00475426, 0.98265088, 1.54599494])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive(підряд) zeros interleaved(чередовані) between each value? (★★★)

In [ ]:
array = np.array([1,2,3,4,5])
nz = 3
array0 = np.zeros(len(array) + (len(array)-1)*(nz)) #масив довжиною з array+колво нульових елементів зо будуть вставлені між елементами 
array0[::nz+1] = array #кожен nz+1 елемент замінюється елементом з array
print(array0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
#створює тривимірний масив  розміром (5, 5, 3), в якому всі елементи мають значення 1. Кожний з трьох вимірів має розмір 5, 5 і 3 відповідно.
print(A * B.reshape(5,5,1)) #e додає нову вісь до Б і робить (5, 5, 1) масив для подальшого множення 

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(25).reshape(5,5)
#np.arange(25) генерує одновимірний масив чисел від 0 до 24.
#reshape(5, 5) перетворює одновимірний масив в матрицю розміром 5x5.

A[[0,1]] = A[[1,0]] #міняє рядки 0 та 1 на 1 та 0 бо в подвійних дужках
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices(спільні вершини)), find the set of unique line segments composing(відрізки прямих зіставляючі) all the  triangles (★★★)

In [ ]:
triangles = np.random.rand(10, 3, 2)
#ривимірний масив triangles, який представляє собою координати вершин 10 випадкових трикутників у двовимірному просторі. Кожен трикутник має 3 вершини (точки) у двовимірному просторі (2D).
# Переформатовуємо до (30, 2), щоб представити всі відрізки
line_segments = triangles.reshape(-1, 2)

# Сортуємо кожен рядок, щоб забезпечити послідовність в представленні сегментів
line_segments.sort(axis=1)

# Використовуємо np.unique для отримання унікальних відрізків
unique_segments = np.unique(line_segments, axis=0)

print("Унікальні відрізки:")
print(unique_segments)

Унікальні відрізки:
[[0.01098009 0.89043951]
 [0.05844135 0.47578018]
 [0.059791   0.84702437]
 [0.07713037 0.62118711]
 [0.07801067 0.11544377]
 [0.08387545 0.7208847 ]
 [0.11668096 0.94214203]
 [0.13138009 0.16083462]
 [0.14901851 0.53915172]
 [0.1526912  0.86344206]
 [0.18231683 0.69122162]
 [0.18914792 0.7402145 ]
 [0.19045687 0.65052205]
 [0.19216019 0.51320043]
 [0.20325073 0.26805891]
 [0.22241217 0.92005106]
 [0.23309907 0.34572929]
 [0.23800993 0.23823864]
 [0.28179647 0.28877991]
 [0.30958475 0.44395079]
 [0.34472716 0.79334275]
 [0.35358183 0.53159767]
 [0.39446398 0.40018061]
 [0.45025771 0.49230026]
 [0.47316607 0.98123148]
 [0.50854652 0.76676892]
 [0.55826298 0.97435452]
 [0.56775953 0.93120398]
 [0.69283955 0.84349821]
 [0.72088084 0.80461102]]


#### 74. Given a sorted array C that corresponds(відповідає) to a bincount, how to produce(зробити) an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6]) 
#кількість входжень кожного цілочисельного значення у введеному масиві
print(C)
print(np.arange(len(C)))
A = np.repeat(np.arange(len(C)), C)#створюємо мас довжиною з С (0,1...6) потім беремо (0,1...6) і С і записуємо числа з (0,1...6) в А кількість разів яка стоїть в С під відповідним індексом (нуль під нулем тому 0 нуль разів,одиниця під двійкою тому 1 два рази)
print(A)

[0 2 1 1 2 0 1]
[0 1 2 3 4 5 6]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window(слизьке вікно) over an array? (★★★)

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view

arr = np.random.randint(0,10,10)
print(arr)

print(sliding_window_view(arr, window_shape=2).mean(axis=1))#бере елементи з arr по 2 кожна ітерація зі зсувом на 1 елемент и у цих пар по рядках рахує середнє

[1 8 9 2 9 1 4 7 5 9]
[4.5 8.5 5.5 5.5 5.  2.5 5.5 6.  7. ]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent(послідовний) row is  shifted(зсувається) by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
array = np.arange(10)
print(sliding_window_view(array, window_shape=3)) # зсув sliding_window_view по 3 елементи

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign(знак) of a float inplace(число з плаваючою точкою)? (★★★)

In [ ]:
array = np.random.randint(0,2,100)
print(array)
print(np.logical_not(array, out=array)) #замінює в array 0 на 1 і 1 на 0

array = np.random.uniform(-1.0,1.0,100)
np.negative(array, out=array)#замінює знак елементів в масиві на протилежний

[0 1 1 1 0 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 1 1 1 0 1 0 1 0
 0 0 0 0 0 0 0 1 0 0 1 1 1 1 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 1 0 1 1 0 1
 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 0]
[1 0 0 0 1 1 0 1 1 0 0 1 0 0 1 1 1 0 0 0 1 0 1 0 1 1 1 0 1 0 0 0 1 0 1 0 1
 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 0 0 1 0 0 1 0
 0 1 1 1 0 0 1 0 1 1 1 1 1 1 1 0 0 0 0 1 1 0 1 1 1 1]


array([-0.90946   , -0.31335523,  0.37623949,  0.53571897,  0.19469864,
       -0.28394722,  0.38817339,  0.67331458,  0.36423051,  0.86475746,
       -0.34574427, -0.1210663 , -0.29806907, -0.02255955, -0.53650344,
        0.95350391, -0.21791619,  0.87060476,  0.51011395,  0.24066664,
       -0.89687834,  0.41400227, -0.50672695, -0.26914575,  0.77680193,
        0.19447461, -0.73829923, -0.13047214, -0.89859703, -0.99387486,
       -0.10799716, -0.67166829, -0.32793608,  0.24298659,  0.25020704,
       -0.89896825,  0.39435699, -0.29186744,  0.80637745,  0.99397168,
       -0.56540096, -0.83411234,  0.85233677, -0.02111975,  0.10819531,
       -0.70850567,  0.0124424 ,  0.65288272,  0.9062886 , -0.52308875,
       -0.53904322,  0.8926698 ,  0.72163824, -0.75725061, -0.398525  ,
        0.32114739,  0.69233744,  0.1372797 , -0.62379211,  0.20799193,
        0.43373736,  0.23824404,  0.88823612, -0.0934221 , -0.09821866,
       -0.59704507,  0.04192145, -0.16991336,  0.64614211, -0.91

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (4,2))
P1 = np.random.uniform(-10, 10, (4,2))
p = np.random.uniform(-10, 10, 2)

print(P0) 
print(P1)
print(p)

def get_distance(P0, P1, p):
    distances = [] #масив відстаней

    for i in range(len(P0)): #цикл до довжини масиву  P0
        a = P1[i][1] - P0[i][1] 
        b = P0[i][0] - P1[i][0]
        c = (P1[i][0] * P0[i][1]) - (P0[i][0] * P1[i][1])

        d = np.abs(a * p[0] + b * p[1] + c)/np.sqrt(a**2 + b**2) #для кожної прямої з пари точок за формулою шукаю відстань до точки  p
        distances.append(d)
    return distances  

print(get_distance(P0,P1,p))

[[ 2.13967485  4.6557666 ]
 [ 7.60477918 -2.13211044]
 [-7.94329594  2.55347581]
 [ 2.32234544 -3.49378042]]
[[ 9.68918055 -8.7728592 ]
 [ 0.09776919 -9.24596788]
 [ 1.86387926 -2.36875405]
 [ 0.40697009 -8.34114875]]
[-4.79869542 -7.25418325]
[11.884682883630465, 4.8137582126488425, 7.354981519701316, 5.240862217158367]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])(для кожної точки з матриці р відстань до кожної прямої з точок р0 р1)? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (4,2))
P1 = np.random.uniform(-10,10,(4,2))
p = np.random.uniform(-10, 10, (4,2))

distances = []

for point in p:
    d = get_distance(P0, P1, point) #функція з 78
    distances.append(d)

print(np.array(distances))

[[17.87568843 15.03071595  1.36623563 10.78072705]
 [ 4.38340411  5.37625354  6.89289212  0.87252394]
 [ 3.01441682 10.97633117  0.56691324  6.31764623]
 [ 2.6388795   6.81161285  4.15759385  2.04895628]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
import numpy as np

def extract_subpart(array, shape, center, fill_value=0):
    """
    Extract a subpart with a fixed shape centered on a given element,
    and pad with a fill value when necessary.

    Parameters:
    - array: input array
    - shape: shape of the subpart
    - center: coordinates of the center element
    - fill_value: value to fill when padding (default is 0)

    Returns:
    - subpart: extracted subpart
    """

    # Calculate half-shape for padding
    half_shape = np.array(shape) // 2

    # Calculate the start and end indices for each axis
    start_indices = np.maximum(center - half_shape, 0)
    end_indices = np.minimum(center + half_shape + 1, array.shape)

    # Initialize the subpart with fill values
    subpart = np.full(shape, fill_value, dtype=array.dtype)

    # Calculate the indices for subpart array
    subpart_start = half_shape - (center - start_indices)
    subpart_end = shape + subpart_start

    # Copy the valid part from the original array to the subpart
    subpart[subpart_start[0]:subpart_end[0], subpart_start[1]:subpart_end[1]] = \
        array[start_indices[0]:end_indices[0], start_indices[1]:end_indices[1]]

    return subpart

# Example usage:
array = np.random.randint(0, 10, (5, 5))
center = np.array([2, 2])
shape = (3, 3)

subpart = extract_subpart(array, shape, center, fill_value=-1)

print("Original Array:")
print(array)
print("Extracted Subpart:")
print(subpart)


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
arr = np.arange(1, 15)
print(sliding_window_view(arr, window_shape=4)) #sliding_window_view по 4 елементи бере

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
array = np.random.uniform(0,1,(10,10))
print(array)
rank = np.linalg.matrix_rank(array)
print(rank)
#Ранг матриці - це максимальна кількість лінійно незалежних стовпців або рядків в матриці

[[0.45191506 0.82645045 0.07206929 0.31186355 0.81303716 0.20441324
  0.87444356 0.50418216 0.57163073 0.10690399]
 [0.64316586 0.52807906 0.5621655  0.94877487 0.64851873 0.26239309
  0.8956034  0.70430356 0.76079821 0.36943583]
 [0.10376761 0.68962137 0.53597523 0.21877876 0.93903249 0.8382024
  0.19785373 0.99835597 0.20905615 0.84368289]
 [0.18743736 0.69034677 0.67881699 0.82228458 0.49341551 0.9521656
  0.23509608 0.37877351 0.96355245 0.81645188]
 [0.38814636 0.52064887 0.2729235  0.78081575 0.67896725 0.3852856
  0.28428201 0.2718372  0.87065548 0.10988227]
 [0.79436344 0.26524702 0.74907501 0.27348787 0.09167492 0.09310537
  0.52915882 0.97360871 0.67461687 0.88302348]
 [0.68508332 0.68154847 0.9566931  0.03224333 0.55597968 0.69650604
  0.34906714 0.19810856 0.53939701 0.54849617]
 [0.39663697 0.25829553 0.7421091  0.06432423 0.54739891 0.05304333
  0.7786538  0.99164153 0.07988354 0.47191258]
 [0.63999984 0.58314308 0.86398891 0.46586294 0.57230264 0.16951962
  0.15834601 0.

#### 83. How to find the most frequent(найчастіше) value in an array?

In [ ]:
array = np.random.randint(0,10,10)
print(array)
# Виклик функції bincount для підрахунку кількості входжень кожного значення
print(np.bincount(array).argmax())#елемент який найчастіше зустрічається в масиві за індексом витягується

[5 5 8 3 1 6 7 6 8 6]
6


#### 84. Extract(вилучити) all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
matrix = np.random.randint(0,5,(10,10))
print(sliding_window_view(matrix, window_shape=(3, 3)))# дістаємо по 3х3 матриці з 10х10 матриці

[[[[2 4 4]
   [3 1 4]
   [1 0 0]]

  [[4 4 1]
   [1 4 2]
   [0 0 1]]

  [[4 1 3]
   [4 2 2]
   [0 1 1]]

  [[1 3 1]
   [2 2 3]
   [1 1 2]]

  [[3 1 4]
   [2 3 0]
   [1 2 2]]

  [[1 4 4]
   [3 0 2]
   [2 2 1]]

  [[4 4 2]
   [0 2 1]
   [2 1 4]]

  [[4 2 2]
   [2 1 2]
   [1 4 0]]]


 [[[3 1 4]
   [1 0 0]
   [1 0 2]]

  [[1 4 2]
   [0 0 1]
   [0 2 1]]

  [[4 2 2]
   [0 1 1]
   [2 1 4]]

  [[2 2 3]
   [1 1 2]
   [1 4 1]]

  [[2 3 0]
   [1 2 2]
   [4 1 3]]

  [[3 0 2]
   [2 2 1]
   [1 3 0]]

  [[0 2 1]
   [2 1 4]
   [3 0 1]]

  [[2 1 2]
   [1 4 0]
   [0 1 1]]]


 [[[1 0 0]
   [1 0 2]
   [1 4 1]]

  [[0 0 1]
   [0 2 1]
   [4 1 4]]

  [[0 1 1]
   [2 1 4]
   [1 4 4]]

  [[1 1 2]
   [1 4 1]
   [4 4 3]]

  [[1 2 2]
   [4 1 3]
   [4 3 2]]

  [[2 2 1]
   [1 3 0]
   [3 2 4]]

  [[2 1 4]
   [3 0 1]
   [2 4 2]]

  [[1 4 0]
   [0 1 1]
   [4 2 3]]]


 [[[1 0 2]
   [1 4 1]
   [1 2 1]]

  [[0 2 1]
   [4 1 4]
   [2 1 2]]

  [[2 1 4]
   [1 4 4]
   [1 2 1]]

  [[1 4 1]
   [4 4 3]
   [2 1 4]]

  [[4 1 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Mirror(np.ndarray): #нащадок ndarray
    def __setitem__(self, index, value): #перевизнячення методу для зміни значення за індексами[2,3]
        i,j = index #розбиваємо index на i,j
        super(Mirror, self).__setitem__((i,j), value)#перевизначаємо в Mirror,вставляємо value на (i,j) кординати
        super(Mirror, self).__setitem__((j,i), value)# ставимо value на симетричному до (i,j) індексі (j,i)

def symetric(array):
    return np.asarray(array + array.T - np.diag(array.diagonal())).view(Mirror) #приймаємо матрицю, додаємо до неї транспоновану-її діагональ view міняє тип масиву на Mirror

array2 = symetric(np.random.randint(0,10,(5,5)))
print(array2)
array2[2,3] = 42
print(array2)

[[ 4  8  9  3 10]
 [ 8  4 13 12 13]
 [ 9 13  3  5  4]
 [ 3 12  5  7  7]
 [10 13  4  7  5]]
[[ 4  8  9  3 10]
 [ 8  4 13 12 13]
 [ 9 13  3 42  4]
 [ 3 12 42  7  7]
 [10 13  4  7  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
array = np.ones((16,16))
k = 4
windows = sliding_window_view(array, (k, k)) #беремо всі блоки 4х4 з 16х16
S = windows[::k, ::k, ...].sum(axis=(1, 0)) #суму кожного 4х4 блоку рахуємо і потім записуємо результати (::k, ::k, ...-беремо з віндовс блок і в sum сумуємо всі рядки стовпці)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement(реалізувати) the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
array = np.arange(10000)
# Створення одновимірного масиву від 0 до 9999

np.random.shuffle(array) # перемішує масив 
print(array)
n = 5

print (array[np.argsort(array)[-n:]]) # argsort повертає індекси значень в зростаючому порядку  і вибираємо n останніх значень

[7425 1385 3100 ... 4987 5892 2563]
[9995 9996 9997 9998 9999]


#### 91. How to create a record(через кому) array from a regular(звичайний) array? (★★★)

In [ ]:
array = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])   # 2 блоку матриця
print(array)
R = np.core.records.fromarrays(array.T,) #транспонована матриця fromarrays робить масив записів з трансп масиву
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3(в степені 3) using 3 different methods (★★★)

In [ ]:
Z = np.random.rand(int(5e7))
print(Z)

print(np.power(Z,3), "mathod1") 
print(Z*Z*Z, "mathod2")
print(np.einsum('i,i,i->i',Z,Z,Z), "mathod3")

[0.90037476 0.82039783 0.42437074 ... 0.96183692 0.66528261 0.21654923]
[0.72991106 0.55217089 0.07642515 ... 0.88982443 0.29445472 0.01015477] mathod1
[0.72991106 0.55217089 0.07642515 ... 0.88982443 0.29445472 0.01015477] mathod2
[0.72991106 0.55217089 0.07642515 ... 0.88982443 0.29445472 0.01015477] mathod3


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless(незалежно від) of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A,B)

C = (A[..., np.newaxis, np.newaxis] == B) # newaxis додає нову вісь до масивів щоб прирівняти їх((8, 3)=(8, 3, 1, 1), (2, 2)=(2, 2, 1, 1) результат булевий С(8, 3, 2, 2)), порівнює кожен елеменнт А з кожним B 
rows = np.where(C.any((3,1)).all(1))[0] #C.any((3,1)) перевірка на хочаб одне тру в 3 і 1 осях (всередині 2x2) .all(1) перевірка А на хочаб одне співпадіння з B np.where повертає індекси по осях де умова виконується
print(rows)

[[1 3 3]
 [2 4 2]
 [3 0 2]
 [0 3 3]
 [3 0 2]
 [4 1 0]
 [0 2 2]
 [2 2 0]] [[4 2]
 [2 1]]
[1 2 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
array = np.random.randint(0,5,(10,3))
unequal = array[array.max(axis=1) != array.min(axis=1),:] #максимальний елем не дорівнює мінімальному
print(unequal)

[[4 2 1]
 [0 2 3]
 [4 2 0]
 [3 3 2]
 [2 0 3]
 [1 3 1]
 [3 0 4]
 [1 0 0]
 [4 0 2]
 [4 0 4]]


#### 95. Convert a vector of ints into a matrix binary representation(бінарне представлення) (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8) 
print(np.unpackbits(I[:, np.newaxis], axis=1)) #робить з вектору інтів вектор в двійковій(бінарний вигляд)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
arr = np.random.randint(0,2,(6,3))
print(arr)
uarr = np.unique(arr, axis=0)
print(uarr)

[[0 0 0]
 [0 0 0]
 [1 1 1]
 [0 1 1]
 [1 1 1]
 [0 1 0]]
[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.randint(0,10,5)
B = np.random.randint(0,10,5)
print(A,B)
      
print(np.einsum('i->', A))# np.sum(A)
print(np.einsum('i,i->i', A, B)) # A * B
print(np.einsum('i,i', A, B))   # np.inner(A, B)(скалярний добуток)
print(np.einsum('i,j->ij', A, B))    # np.outer(A, B) (зовнішній добуток матриць(поелементно кожний на кожного))

[4 8 2 3 1] [6 8 5 6 8]
18
[24 64 10 18  8]
124
[[24 32 20 24 32]
 [48 64 40 48 64]
 [12 16 10 12 16]
 [18 24 15 18 24]
 [ 6  8  5  6  8]]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
#ядки сума яких=n і тількир з інтеджерами
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=1) #перевірка на ціле число np.mod(X, 1)-остача від ділення кожного елементу матриці на 1.0 результат після коми запишеться logical_and.reduce змінює отримані числа на тру фолс
M &= (X.sum(axis=1) == n) #перевірка на сума=n і результат з M об'єднується
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence(довіра) intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randint(0, 100, 100)
N = 1000 # колво бутстрап-операцій
idx = np.random.randint(0, X.size, (N, X.size)) #генерація матриці індексів бутстрап-виборок
means = X[idx].mean(axis=1) #вибір вибірок , середнє з кожної вибірки 
print(means)
percentiles = np.percentile(means, 95)#95% середіх з вибірок меньше ніж резуьтат рядка
print(percentiles)

[44.64 43.56 44.4  45.06 45.95 42.45 50.78 46.39 44.82 44.36 42.55 49.74
 45.66 44.95 46.02 47.09 45.93 47.25 44.33 47.3  41.41 47.99 42.08 47.06
 50.55 46.38 49.14 43.5  46.71 50.   50.77 40.87 45.53 46.51 49.42 47.33
 46.13 45.73 53.74 49.43 47.24 46.99 42.22 46.64 48.28 47.16 46.03 45.34
 47.77 51.42 49.08 45.44 47.83 51.42 46.22 49.32 47.51 48.49 46.37 46.18
 47.77 42.38 44.36 50.25 46.23 46.3  45.94 48.16 47.03 49.97 44.88 46.64
 49.34 43.1  43.04 40.88 45.86 42.16 46.52 49.71 48.96 44.58 39.87 49.61
 48.19 45.27 47.56 40.13 48.96 46.57 44.44 50.55 46.71 50.38 48.37 45.55
 51.48 45.3  50.15 49.03 45.75 39.71 45.33 46.94 49.94 51.53 46.18 46.71
 47.86 50.2  47.92 48.32 47.98 46.88 48.64 46.36 49.27 50.31 45.6  44.49
 44.47 46.61 46.13 46.57 42.04 44.61 47.78 50.96 44.92 47.14 51.18 46.28
 43.99 47.7  44.04 46.21 50.28 44.17 46.33 47.47 43.94 42.21 49.9  43.41
 48.02 45.77 47.2  43.82 43.51 47.89 46.88 43.78 51.5  46.87 46.05 44.25
 44.23 48.73 43.37 45.52 46.38 44.5  49.97 43.14 47